git:
  project_directory: /home/getracing/Desktop/get/jarvic-mono/
  track_files:
   - src/2_estimation/fastslam/config/fastslam_fssim.yaml



oauth:
  client_id: eeb2fc864632a0d97159329e35207be737efc6df3c9f0ccc2dcb1a92197ca8dc
  client_secret: gloas-544cca91b6282ab73ceaf6ad6d597d31d54787085d95ac9b9fdda63d2cd24193
  issuer: https://gitlab.fachschaften.org
  discovery_url: https://gitlab.fachschaften.org/.well-known/openid-configuration

gitlab:
  project_id: "448"



# Name input to 'x', and output to 'value'
# titles should be unique


scripts:
- label: blue_cones
  topic: /jarvic/estimation/map
  code: |
    def ahah(x):
      return len(x['cones'])
    value = ahah(x)
- label: clock
  topic: /clock
  code: |
    value = x['clock']['secs']

